<?php

return [


    'NEWS_CATEGORY_ID' => 1,
    'EVENT_CATEGORY_ID' => 2,


    'FRONTEND_CACHE_TIME' => 5,



    'GAME_CONTENT_TYPE_TRAILER' => 1,
    'GAME_CONTENT_TYPE_ARTWORK_SLIDER' => 2,
    'GAME_CONTENT_TYPE_CHARACTER_SLIDER' => 3,
    'GAME_CONTENT_TYPE_MISSION_LIST' => 4,
    'GAME_CONTENT_TYPE_PET_SLIDER' => 5,
    'GAME_CONTENT_TYPE_SKILL_LIST' => 6,
    'GAME_CONTENT_TYPE_TOGETHER_SLIDER' => 7,
    'GAME_CONTENT_TYPE_FUNCTION_LIST' => 8,
];